services:
  nginx:
    depends_on:
      - wordpress
    container_name: nginx
    env_file:
      - ./.env
    image: nginx:final
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - wordpress:/var/www/html/wordpress
    ports:
      - "443:443"
    networks:
      - inception

  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    env_file:
      - ./.env
    image: wordpress:final
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - wordpress:/var/www/html/wordpress
    expose:
      - "9000"
    networks:
      - inception

  mariadb:
    container_name: mariadb
    env_file:
      - ./.env
    image: mariadb:final
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
        - DB_ROOT_PASS=${DB_ROOT_PASS}
        - DB_CONF_ROUTE=${DB_CONF_ROUTE}
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    networks:
      - inception

networks:
  inception:
    name: inception

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'nfs'
      o: 'bind'
      # device: '/home/mdanish/data/wordpress'
      device: '../data/wordpress'

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'nfs'
      o: 'bind'
      # device: '/home/mdanish/data/mariadb'
      device: '../data/mariadb'
